Update trilomorph.yaml
balsedie/trilomorph pull request #58
Opened 2024-09-12 19:04 UTC by Damian-Aquino

[NUF5274_P.txt](https://github.com/user-attachments/files/16984410/NUF5274_P.txt)
[NUF5274_P.txt](https://github.com/user-attachments/files/16984410/NUF5274_P.txt)
[SMF_57466_P.txt](https://github.com/user-attachments/files/16984411/SMF_57466_P.txt)
[SMF_57466_P.txt](https://github.com/user-attachments/files/16984411/SMF_57466_P.txt)
[KUMIP_146475_P.txt](https://github.com/user-attachments/files/16984412/KUMIP_146475_P.txt)
[KUMIP_146475_P.txt](https://github.com/user-attachments/files/16984412/KUMIP_146475_P.txt)
[CMNH_34436_P.txt](https://github.com/user-attachments/files/16984413/CMNH_34436_P.txt)
[CMNH_34436_P.txt](https://github.com/user-attachments/files/16984413/CMNH_34436_P.txt)
[CM_45119_P.txt](https://github.com/user-attachments/files/16984414/CM_45119_P.txt)
[CM_45119_P.txt](https://github.com/user-attachments/files/16984414/CM_45119_P.txt)
[QMF17-1233_P.txt](https://github.com/user-attachments/files/16984415/QMF17-1233_P.txt)
[QMF17-1233_P.txt](https://github.com/user-attachments/files/16984415/QMF17-1233_P.txt)
[SMF_57452_P.txt](https://github.com/user-attachments/files/16984416/SMF_57452_P.txt)
[SMF_57452_P.txt](https://github.com/user-attachments/files/16984416/SMF_57452_P.txt)
[CM_45765_P.txt](https://github.com/user-attachments/files/16984417/CM_45765_P.txt)
[CM_45765_P.txt](https://github.com/user-attachments/files/16984417/CM_45765_P.txt)
![CM_45765_P](https://github.com/user-attachments/assets/46ca0cbf-7ef1-4d38-b206-355298426bb5)
![CM_45765_P](https://github.com/user-attachments/assets/46ca0cbf-7ef1-4d38-b206-355298426bb5)
![CMNH_34436_P](https://github.com/user-attachments/assets/35dfab61-62b4-4a62-8887-587109f7c6ab)
![CMNH_34436_P](https://github.com/user-attachments/assets/35dfab61-62b4-4a62-8887-587109f7c6ab)
![KUMIP_146475_P](https://github.com/user-attachments/assets/d96b186f-a485-4f60-bd97-108f910a0f33)
![KUMIP_146475_P](https://github.com/user-attachments/assets/d96b186f-a485-4f60-bd97-108f910a0f33)
![NUF5274_P](https://github.com/user-attachments/assets/b496c3d6-7197-42ec-8fc2-dc190350fe75)
![NUF5274_P](https://github.com/user-attachments/assets/b496c3d6-7197-42ec-8fc2-dc190350fe75)
![QMF17-1233_P](https://github.com/user-attachments/assets/72af74ea-9937-4b96-8de5-37de1b120d3f)
![QMF17-1233_P](https://github.com/user-attachments/assets/72af74ea-9937-4b96-8de5-37de1b120d3f)
![SMF_57452_P](https://github.com/user-attachments/assets/1dc4ffac-221f-48b5-a4a5-24c8c60d10a3)
![SMF_57452_P](https://github.com/user-attachments/assets/1dc4ffac-221f-48b5-a4a5-24c8c60d10a3)
![SMF_57466_P](https://github.com/user-attachments/assets/21c408f3-5391-47e6-b107-d1c55622bcff)
![SMF_57466_P](https://github.com/user-attachments/assets/21c408f3-5391-47e6-b107-d1c55622bcff)
![CM_45119_P](https://github.com/user-attachments/assets/e40dda78-4552-4444-99fd-fd7bcc116f00)
![CM_45119_P](https://github.com/user-attachments/assets/e40dda78-4552-4444-99fd-fd7bcc116f00)

2024-09-12 19:08 UTC, Damian-Aquino commented
![CM_45765_P](https://github.com/user-attachments/assets/5c1732bf-d945-46c6-b649-adc82c8605b2)
![CMNH_34436_P](https://github.com/user-attachments/assets/dc28b1e8-e3fa-48bd-860a-6699a050e389)
![KUMIP_146475_P](https://github.com/user-attachments/assets/a35555a5-9cc1-46e6-90f8-8e2899eb9972)
![NUF5274_P](https://github.com/user-attachments/assets/0b023594-981f-4da1-abf2-3435908e2c86)
![QMF17-1233_P](https://github.com/user-attachments/assets/c982f254-cb7d-4ee5-ae06-9a0e52d78d8d)
![SMF_57452_P](https://github.com/user-attachments/assets/0c07ef67-cf08-4701-a806-227b4a1522f6)
![SMF_57466_P](https://github.com/user-attachments/assets/f9108d17-9a52-4daf-8461-88506a3f66ca)
![CM_45119_P](https://github.com/user-attachments/assets/45dfd227-3fd9-4434-9cba-b29245fdf07a)
[CMNH_34436_P.txt](https://github.com/user-attachments/files/16984456/CMNH_34436_P.txt)
[CM_45119_P.txt](https://github.com/user-attachments/files/16984457/CM_45119_P.txt)
[QMF17-1233_P.txt](https://github.com/user-attachments/files/16984458/QMF17-1233_P.txt)
[SMF_57452_P.txt](https://github.com/user-attachments/files/16984459/SMF_57452_P.txt)
[CM_45765_P.txt](https://github.com/user-attachments/files/16984460/CM_45765_P.txt)
[NUF5274_P.txt](https://github.com/user-attachments/files/16984461/NUF5274_P.txt)
[SMF_57466_P.txt](https://github.com/user-attachments/files/16984462/SMF_57466_P.txt)
[KUMIP_146475_P.txt](https://github.com/user-attachments/files/16984463/KUMIP_146475_P.txt)

2024-09-13 17:38 UTC, balsedie requested changes
Dami, fijate que 
1) en todos (excepto uno) los ID: faltan los dos espacios antes (indentación). Tiene que estar alineado con taxonomy:
2) las líneas 37, 76,  tiene un espacio de más al inicio
3) las líneas 154, 193 tiene un espacio de menos
4) en la línea 221 falta el NA
5) las líneas 26, 65, 104 y 143 dicen country en vez de county
6) usa carbonate en vez de carbonatic
7) por seguridad nomás eliminá todas las comas de las citas (ej. líneas 12 y 13)
8) en la línea 432 (ex línea 120) el ID viejo estaba bien. Fijate que si o si debe llamarse como el archivo y por ende no puede tener / % & u otros símbolos que o se aceptan para el nombre de archivo .txt

2024-09-18 17:05 UTC, Damian-Aquino commented
Diego el ID de la linea 432(ex 120) figura de esa manera en el paper, yo le puse guion en su momento porque asi habia guardado la imagen y no podia guardarla con la barra y arrastre el cambio a la metadata

2024-09-18 19:58 UTC, balsedie approved these changes

2024-09-18 19:58 UTC, merged